# canyoutle/wxdt:base
FROM dorowu/ubuntu-desktop-lxde-vnc:bionic

ENV LANG C.UTF-8
ENV DISPLAY :1.0
ENV HOME /root
RUN echo "Asia/Shanghai" > /etc/timezone
RUN dpkg-reconfigure -f noninteractive tzdata

RUN sed -i 's#http://\(archive\|security\).ubuntu.com/#http://mirrors.aliyun.com/#' /etc/apt/sources.list \
  && cat /etc/apt/sources.list
RUN apt-get update \
  && apt-get install -y --no-install-recommends --allow-unauthenticated \
    wget \
    curl \
    p7zip-full \
    gpg-agent \
    dbus \
    libgconf-2-4 \
    build-essential \
    ca-certificates \
    openssl \
    python2.7 \
    gnupg2

RUN echo "\n\
[program:wxdt]\n\
priority=25\n\
directory=/wxdt/bin/\n\
command=bash wxdt start\n\
stderr_logfile=/var/log/wxdt.err.log\n\
stdout_logfile=/var/log/wxdt.out.log\n\
" >> /etc/supervisor/conf.d/supervisord.conf

# # install wine-binfmt
# RUN apt-get install -y --no-install-recommends --allow-unauthenticated \
#     wine-binfmt
# RUN update-binfmts --import /usr/share/binfmts/wine

# install wine and config wine
RUN dpkg --add-architecture i386 \
  && wget -nc https://dl.winehq.org/wine-builds/winehq.key \
  && apt-key add winehq.key \
  && apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ bionic main' \
  && apt-get update \
  && apt-get install -y --no-install-recommends --allow-unauthenticated winehq-stable

# install nodejs
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs

# # 构建dockerfile
# docker build -t canyoutle/wxdt-desktop:prebase -f Dockerfile-base .
# docker-machine ip # 获得ip
# # 运行容器
# docker run -d --rm -name wxdt-base -P -p 6080:80 --mount type=bind,source=$PWD,target=/wxdt canyoutle/wxdt-desktop:prebase
# # 然后在浏览器中打开 http://ip:6080 `docker-machine ip`获得的ip
# # 在容器内安装
# docker exec -it wxdt-base /wxdt/bin/wxdt install
# docker exec -it wxdt-base /root/.config/wechat_web_devtools/WeappVendor/wcc.exe # 会自动启动wine配置
# docker commit wxdt-base canyoutle/wxdt:base
